### ISSUE TITLE
Get up-to-date figures from ms, SI -> slides

### ISSUE THREAD

**Issue by rvanmazijk** [rvanmazijk/Cape-vs-SWA#115]
- [x] Context map (#122)
- [x] Figure S4: PCA biplots (modified version from MEDECOS 2020) (#123)
- [x] Figure 1a–d: richness, PC1 maps (#123)
- [x] Figure 4: richness vs PC1 (#124)
- [x] Figure S5: PC1-based outliers (#124)
