### ISSUE TITLE
Remake figures to be more talk-friendly, as needed

### ISSUE THREAD

**Issue by rvanmazijk** [rvanmazijk/Cape-vs-SWA#118]
Re: #115.

- [x] Figure 1a–d: richness, PC1 maps (#123)
  - [x] Vertical colour ramps 
  - [x] Coloured region headings
- [x] & all figures w/ new colour scheme (#127)? Namely:
  - [x] Context map (#122)
  - [x] Figure S4: PCA biplots (#123)
  - [x] Figure 4: richness vs PC1 (#124)
